#18/01/23
#2ns r project - git linked one
#created new repo on website called frog-riddler
#go to code on repo and copy link
# then make new r project and use the repository version and choose git
#make edits then commit to update
#can go to diff revert to go back one step#carry on saving as normal
#need to add file to get git to watch it
#check tickboxes in git tab to commit changes for each file you're wirking on

#so far all on local directory so go to push arrow to add to website
# push pushes everything you've done since lst push - no need to select things

#how often to commit, which gives you breaks in your edits? not daily but not every line
#don't commit big data files from the environment
#don't commit pdf, ppt, word as you will get multiple copies adn fill your PC
#but maybe commit word, pdf etc once at the end

#gitignore tells git not to keep backing up all the r system etc files that are autogenerated for each proj
#can edit .gitignore to add file type eg
# Ignore extra files
#*.ppt
#*.docx
#*etc